spring:
  application:
    name: eurekaclient1
  profiles:
    active: default
  cloud:
    stream:
      bindings:
        input:
          destination : orgChangeTopic
          conetnt-type : application/json
          group: eurekaClient1
        binder:
          brokers: localhost
          zkNodes: localhost

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/



server:
  port: 8181