
server:
  servlet:
    session:
      timeout: 1000

spring:
  redis:
    host: localhost
    password: 1234
    port: 6397
  session:
    redis:
      flush-mode: on_save
      namespace: spring:session
    store-type: redis


