
server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: utf-8
      enabled: true
spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 65042798307-j7fa7o7d22m1nthjh32jh5blfg4551p5.apps.googleusercontent.com
            client-secret: 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
            scope:
            - email
            - profile

    user:
      name: java
      password: 1234

#  h2:
#    console:
#      enabled: true
#      settings:
#        web-allow-others: false
#      path: /h2-console
  datasource:
    url: jdbc:mysql://localhost:3306/securityexample?serverTimezone=Asia/Seoul
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: java
    password: 1234


  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    open-in-view: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org:
      hibernate:
        SQL: debug
        type:
          descriptor:
            sql: trace




# 1.?? 2.?? 3.http ???? ???? ?? ??, csrf, cors, 4.oauth2.0